### ISSUE TITLE
Unable to find css ".datepicker"

### ISSUE THREAD

**Issue by Ana06** [akarzim/capybara-bootstrap-datepicker#14]
I am using bootstrap3-datetimepicker-rails 4.17.47, capybara-bootstrap-datepicker 0.1.2, capybara 3.12.0 and rspec 3.6.0.

I have the following code in Rails:

```ruby
= f.input :start_date, as: :string, input_html: { class: 'form-control', id: 'registration-period-start-datapicker' }
```

With this JavaScript:

```JavaScript
$('#registration-period-start-datapicker').datetimepicker({
     format: 'YYYY-MM-DD',
     minDate : today,
     maxDate : end_conference
});
```

the generated html:
```html
<div class="string input required stringish form-group" id="cfp_start_date_input"><span class="form-label"><label for="registration-period-start-datapicker" class=" control-label">Start date&nbsp;<span class="text-warning"><abbr title="This field is required">*</abbr></span></label></span><span class="form-wrapper"><input id="registration-period-start-datapicker" class="form-control form-control" type="text" name="cfp[start_date]"></span></div>
```

The rspec test:

```ruby
start_date = Date.today + 1.days
end_date = start_date + 6.days

select_date(start_date, from: 'Start date')
select_date(end_date, from: 'End date')
```

the error:
```
  1) Conference organizer behaves like add and update cfp adds a new cfp
     Failure/Error: select_date(start_date, from: 'Start date')
     
     Capybara::ElementNotFound:
       Unable to find css ".datepicker" within #<Capybara::Node::Element tag="body" path="/HTML/BODY">
     Shared Example Group: "add and update cfp" called from ./spec/features/cfp_spec.rb:72
     # ./spec/features/cfp_spec.rb:29:in `block (3 levels) in <top (required)>'
```

Original code: https://github.com/openSUSE/osem/compare/master...Ana06:datepickers-gem?expand=1

Maybe related to: https://github.com/akarzim/capybara-bootstrap-datepicker/issues/3

Issue in bootstrap3-datetimepicker-rails: https://github.com/TrevorS/bootstrap3-datetimepicker-rails/issues/66

**Comment by akarzim** [comment]
Hi @Ana06,

Thank you for your detailed report. I found time to investigate and I observed the same behaviour as you in the first place. Looking at your PR on openSUSE/osem, it seems that you don't need to manage time anyway. So, by using `datepicker` instead of `datetimepicker` in your JS code, and then changing the date format to lowercase `yyyya-mm-dd`, I now have green tests.

By the way, I just upgraded the gem to 0.2.0 with more test cases and support for Bootstrap 4.4 :tada:

I hope it will help you!
