### ISSUE TITLE
Is RSpec required?

### ISSUE THREAD

**Issue by kevinansfield** [akarzim/capybara-bootstrap-datepicker#5]
I'm using MiniTest but after adding this gem I noticed that all of RSpec gets pulled in too. Is that a hard requirement?

**Comment by akarzim** [comment]
Hi Kevin,

I have always used it with RSpec. I'll try to remove this dependency. You
can also create a pull request if you have any time.

**Comment by kevinansfield** [comment]
For now I have just pulled out the main module and included that. If I find some time I’ll definitely look at making a pull request.

**Comment by akarzim** [comment]
I've just released a new version (0.1.0) of this gem. There is no strong dependency with rspec anymore.
Feel free to make a pull request with a MiniTest config file just as I did for Rspec if it can help others.
